-- Seed artworks table with 12 public-domain European masters
INSERT INTO public.artworks (title, artist, year, image_url, description, historical_context, tags, space_suitability, base_price_cad, prodigi_sku_base) VALUES

('Girl with a Pearl Earring', 'Johannes Vermeer', 'c.1665',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg',
 'A luminous portrait of a young woman turning towards the viewer, her lips slightly parted, wearing an exotic turban and an oversized pearl earring that catches the light against a dark background.',
 'Often called the "Mona Lisa of the North", this masterpiece resides in the Mauritshuis, The Hague. Vermeer created it during the Dutch Golden Age, and the identity of the sitter remains one of art history''s great mysteries. The ultramarine turban was painted with costly lapis lazuli pigment.',
 ARRAY['Intimate', 'Classic', 'Portrait', 'Serene', 'Gold'],
 ARRAY['Hotel Room', 'Residential', 'Office'],
 49.99, 'GLOBAL-FAP'),

('Starry Night', 'Vincent van Gogh', '1889',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
 'A swirling night sky over a village, with bold spiralling clouds, a luminous crescent moon, and a towering cypress tree in the foreground. The thick impasto brushwork creates a sense of turbulent energy.',
 'Painted from memory during Van Gogh''s stay at the Saint-Paul-de-Mausole asylum in Saint-Rémy-de-Provence. Now in the Museum of Modern Art, New York. It has become one of the most recognised paintings in Western culture.',
 ARRAY['Dramatic', 'Blue', 'Expressive', 'Iconic'],
 ARRAY['Hotel Lobby', 'Restaurant', 'Residential'],
 49.99, 'GLOBAL-FAP'),

('The Great Wave off Kanagawa', 'Katsushika Hokusai', 'c.1831',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg',
 'A towering wave with foam tendrils curls over fishing boats, with Mount Fuji sitting serenely in the background. The composition balances immense natural power with delicate line work.',
 'Part of Hokusai''s series "Thirty-six Views of Mount Fuji", this woodblock print profoundly influenced European Impressionists. Multiple impressions exist in museums worldwide including the Metropolitan Museum of Art and the British Museum.',
 ARRAY['Dynamic', 'Blue', 'Nature', 'Iconic', 'Japanese'],
 ARRAY['Hotel Lobby', 'Restaurant', 'Office', 'Hallway/Corridor'],
 44.99, 'GLOBAL-FAP'),

('The Birth of Venus', 'Sandro Botticelli', 'c.1485',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg',
 'Venus emerges from the sea as a fully grown woman, standing on a giant scallop shell. Zephyr and Chloris blow her towards shore where a Hora waits with a floral cloak. The ethereal palette of soft pinks and seafoam greens creates a dreamlike atmosphere.',
 'Commissioned by the Medici family, this tempera on canvas is housed in the Uffizi Gallery, Florence. It represents the arrival of beauty into the world and is one of the supreme achievements of Renaissance painting.',
 ARRAY['Elegant', 'Classical', 'Mythological', 'Warm', 'Renaissance'],
 ARRAY['Hotel Lobby', 'Hotel Dining', 'Residential'],
 54.99, 'GLOBAL-FAP'),

('Water Lilies', 'Claude Monet', '1906',
 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg',
 'A serene pond surface covered with floating lily pads and delicate blooms, reflected clouds dissolving into shimmering water. The composition has no horizon line — the viewer is immersed entirely in the water''s surface.',
 'Part of Monet''s monumental Water Lilies series of approximately 250 paintings. This work from the Art Institute of Chicago captures his garden at Giverny. The series influenced Abstract Expressionism decades later.',
 ARRAY['Serene', 'Nature', 'Blue', 'Green', 'Impressionist'],
 ARRAY['Hotel Room', 'Hotel Lobby', 'Office', 'Residential', 'Restaurant'],
 49.99, 'GLOBAL-FAP'),

('The Kiss', 'Gustav Klimt', '1907–1908',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/800px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg',
 'A couple wrapped in an embrace on a flower-strewn cliff edge, their bodies merged into a single golden form. The man''s geometric rectangles contrast with the woman''s circular floral patterns.',
 'The pinnacle of Klimt''s Golden Phase, housed in the Österreichische Galerie Belvedere, Vienna. Created with oil paint and gold leaf on canvas, it epitomises Art Nouveau''s synthesis of fine art and decorative design.',
 ARRAY['Romantic', 'Gold', 'Decorative', 'Art Nouveau', 'Iconic'],
 ARRAY['Hotel Room', 'Residential', 'Restaurant'],
 54.99, 'GLOBAL-FAP'),

('Wanderer above the Sea of Fog', 'Caspar David Friedrich', 'c.1818',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg',
 'A man in a dark frock coat stands on a rocky precipice, his back to the viewer, gazing across a vast landscape of fog-shrouded peaks. The figure is both dwarfed by and commanding over the sublime natural scene.',
 'The quintessential Romantic painting, now in the Hamburger Kunsthalle. Friedrich''s use of the Rückenfigur — a figure seen from behind — invites the viewer to share the subject''s contemplation of nature''s grandeur.',
 ARRAY['Dramatic', 'Nature', 'Romantic', 'Contemplative'],
 ARRAY['Hotel Lobby', 'Office', 'Hallway/Corridor'],
 49.99, 'GLOBAL-FAP'),

('A Sunday on La Grande Jatte', 'Georges Seurat', '1884–1886',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg',
 'Parisians enjoy a sunny afternoon on an island in the Seine. Figures stand, sit, and stroll with geometric precision. The painting''s surface shimmers with millions of tiny dots of pure colour.',
 'The masterwork of Pointillism, housed at the Art Institute of Chicago. Seurat spent two years applying his scientific colour theory, placing complementary dots side by side so the eye blends them at distance.',
 ARRAY['Serene', 'Bright', 'Impressionist', 'Social', 'Pastoral'],
 ARRAY['Hotel Dining', 'Restaurant', 'Hotel Lobby', 'Residential'],
 54.99, 'GLOBAL-FAP'),

('The Persistence of Memory', 'Salvador Dalí', '1931',
 'https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg',
 'Melting pocket watches drape over a barren landscape and a strange fleshy form. A single hard watch is overrun by ants. The dreamlike scene is rendered with photographic precision against the cliffs of Port Lligat.',
 'A defining Surrealist work in the Museum of Modern Art, New York. Dalí described the soft watches as inspired by the surrealist perception of a Camembert cheese melting in the sun. The tiny canvas (24×33 cm) belies its enormous cultural impact.',
 ARRAY['Surreal', 'Dramatic', 'Contemplative', 'Iconic'],
 ARRAY['Office', 'Hotel Room', 'Residential'],
 49.99, 'GLOBAL-FAP'),

('Impression, Sunrise', 'Claude Monet', '1872',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/1280px-Monet_-_Impression%2C_Sunrise.jpg',
 'A misty harbour at dawn rendered in loose, rapid brushstrokes. An orange sun hovers over blue-grey water, its reflection a few dashes of vivid colour. Industrial cranes and masts dissolve into morning haze.',
 'The painting that gave Impressionism its name — shown at the first Impressionist exhibition in 1874. Now in the Musée Marmottan Monet, Paris. Critic Louis Leroy used the title mockingly, but the artists embraced it.',
 ARRAY['Serene', 'Blue', 'Impressionist', 'Warm', 'Harbour'],
 ARRAY['Hotel Lobby', 'Office', 'Restaurant', 'Residential'],
 49.99, 'GLOBAL-FAP'),

('Nighthawks', 'Edward Hopper', '1942',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/1280px-Nighthawks_by_Edward_Hopper_1942.jpg',
 'Four figures sit in a brightly lit downtown diner late at night, visible through a large glass window. The empty street outside amplifies the sense of urban isolation. Sharp fluorescent light contrasts with deep shadow.',
 'America''s most iconic painting of urban solitude, housed at the Art Institute of Chicago. Hopper said "unconsciously, probably, I was painting the loneliness of a large city." The diner has no visible entrance.',
 ARRAY['Urban', 'Dramatic', 'Contemplative', 'Night', 'American'],
 ARRAY['Restaurant', 'Hotel Lobby', 'Office', 'Hallway/Corridor'],
 49.99, 'GLOBAL-FAP'),

('The Arnolfini Portrait', 'Jan van Eyck', '1434',
 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/800px-Van_Eyck_-_Arnolfini_Portrait.jpg',
 'A wealthy couple stands in a richly furnished bedchamber. Every surface gleams with meticulous detail — a brass chandelier, a convex mirror reflecting the room, oranges on the windowsill, a small dog at their feet.',
 'One of the earliest major works in oil paint, now in the National Gallery, London. Van Eyck''s inscription "Johannes de eyck fuit hic" (Jan van Eyck was here) and the mirror reflection have fuelled centuries of debate about the painting''s purpose.',
 ARRAY['Intimate', 'Classic', 'Portrait', 'Detailed', 'Gold'],
 ARRAY['Hotel Room', 'Residential', 'Office'],
 49.99, 'GLOBAL-FAP');
